cli:
    show_service_info: true
connectivity:
    enabled: false
    mdns:
        enabled: false
    tunnel:
        provider: cloudflare
project:
    name: whi
    type: custom
resources:
    memory_limit: 4GB
    cpu_limit: "2"
services:
    ai:
        port: 11434
        models:
            - qwen2.5:3b
        default: qwen2.5:3b
    database:
        type: postgres
        version: "16"
        port: 5432
    cache:
        type: redis
        port: 6379
        maxmemory: 512mb
        maxmemory_policy: allkeys-lru
        persistence: false
    queue:
        type: redis
        port: 6380
        maxmemory: 1gb
        maxmemory_policy: noeviction
        persistence: true
        appendonly: true
        appendfsync: everysec
    storage:
        type: minio
        port: 9000
        console: 9001
version: "1"
