cli:
    show_service_info: true
connectivity:
    enabled: false
    mdns:
        enabled: false
    tunnel:
        provider: cloudflare
project:
    name: aa
    type: custom
    components: []
resources:
    memory_limit: 4GB
    cpu_limit: "2"
services:
    ai:
        port: 0
        models: []
        default: ""
    database:
        type: ""
        version: ""
        port: 0
    cache:
        type: ""
        port: 0
        maxmemory: ""
        maxmemory_policy: ""
        persistence: false
    queue:
        type: ""
        port: 0
        maxmemory: ""
        maxmemory_policy: ""
        persistence: false
        appendonly: false
        appendfsync: ""
    storage:
        type: ""
        port: 0
        console: 0
    whisper:
        type: ""
        port: 0
        model: ""
version: "1"
