cli:
    showserviceinfo: true
connectivity:
    enabled: false
    mdns:
        enabled: false
    tunnel:
        provider: cloudflare
        persist: false
        domain: ""
        targeturl: ""
        cloudflare:
            tunnelid: ""
            credentials: ""
        ngrok:
            authtoken: ""
            region: ""
project:
    name: my-test-app
    type: custom
resources:
    memorylimit: 4GB
    cpulimit: "2"
services:
    ai:
        port: 11434
        models:
            - qwen2.5:3b
        default: qwen2.5:3b
    database:
        type: postgres
        version: "16"
        port: 5432
        extensions: []
    cache:
        type: redis
        port: 6379
        maxmemory: 512mb
        maxmemorypolicy: allkeys-lru
        persistence: false
    queue:
        type: redis
        port: 6380
        maxmemory: 1gb
        maxmemorypolicy: noeviction
        persistence: true
        appendonly: true
        appendfsync: everysec
    storage:
        type: minio
        port: 9000
        console: 9001
version: "1"
